CREATE TABLE accounting_child_payments
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active     BOOLEAN,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    update_at     TIMESTAMP WITHOUT TIME ZONE,
    child_id      BIGINT                                  NOT NULL,
    payment_month date                                    NOT NULL,
    amount        DECIMAL(19, 2)                          NOT NULL,
    paid_date     date,
    status        VARCHAR(255)                            NOT NULL,
    description   VARCHAR(1000),
    CONSTRAINT pk_accounting_child_payments PRIMARY KEY (id)
);

CREATE TABLE accounting_expenses
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active    BOOLEAN,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    update_at    TIMESTAMP WITHOUT TIME ZONE,
    category     VARCHAR(255)                            NOT NULL,
    title        VARCHAR(500)                            NOT NULL,
    amount       DECIMAL(19, 2)                          NOT NULL,
    expense_date date                                    NOT NULL,
    description  VARCHAR(1000),
    receipt_url  VARCHAR(1000),
    CONSTRAINT pk_accounting_expenses PRIMARY KEY (id)
);

CREATE TABLE accounting_teacher_salaries
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active    BOOLEAN,
    created_at   TIMESTAMP WITHOUT TIME ZONE,
    update_at    TIMESTAMP WITHOUT TIME ZONE,
    teacher_id   BIGINT                                  NOT NULL,
    salary_month date                                    NOT NULL,
    amount       DECIMAL(19, 2)                          NOT NULL,
    paid_date    date,
    status       VARCHAR(255)                            NOT NULL,
    description  VARCHAR(1000),
    CONSTRAINT pk_accounting_teacher_salaries PRIMARY KEY (id)
);

CREATE TABLE children
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active         BOOLEAN,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    update_at         TIMESTAMP WITHOUT TIME ZONE,
    first_name        VARCHAR(255),
    last_name         VARCHAR(255),
    patronymic        VARCHAR(255),
    age               INTEGER,
    gender            VARCHAR(255),
    birth_date        date,
    mother_first_name VARCHAR(255),
    mother_last_name  VARCHAR(255),
    father_first_name VARCHAR(255),
    father_last_name  VARCHAR(255),
    mother_phone      VARCHAR(255),
    father_phone      VARCHAR(255),
    group_id          BIGINT,
    address           VARCHAR(255),
    CONSTRAINT pk_children PRIMARY KEY (id)
);

CREATE TABLE daily
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active  BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    update_at  TIMESTAMP WITHOUT TIME ZONE,
    date       date,
    is_present BOOLEAN,
    child_id   BIGINT                                  NOT NULL,
    CONSTRAINT pk_daily PRIMARY KEY (id)
);

CREATE TABLE groups
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active  BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    update_at  TIMESTAMP WITHOUT TIME ZONE,
    name       VARCHAR(255),
    teacher_id BIGINT,
    CONSTRAINT pk_groups PRIMARY KEY (id)
);

CREATE TABLE others
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active     BOOLEAN,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    update_at     TIMESTAMP WITHOUT TIME ZONE,
    first_name    VARCHAR(255),
    last_name     VARCHAR(255),
    phone         VARCHAR(255),
    profession    VARCHAR(255),
    date_of_birth date,
    start_date    date,
    end_date      date,
    CONSTRAINT pk_others PRIMARY KEY (id)
);

CREATE TABLE roles
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active  BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    update_at  TIMESTAMP WITHOUT TIME ZONE,
    role       VARCHAR(255),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    is_active  BOOLEAN,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    update_at  TIMESTAMP WITHOUT TIME ZONE,
    email      VARCHAR(255),
    password   VARCHAR(255),
    first_name VARCHAR(255),
    last_name  VARCHAR(255),
    phone      VARCHAR(255),
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE users_roles
(
    user_id  BIGINT NOT NULL,
    roles_id BIGINT NOT NULL
);

ALTER TABLE groups
    ADD CONSTRAINT uc_groups_teacher UNIQUE (teacher_id);

ALTER TABLE daily
    ADD CONSTRAINT uk_daily_child_date UNIQUE (child_id, date);

ALTER TABLE children
    ADD CONSTRAINT FK_CHILDREN_ON_GROUP FOREIGN KEY (group_id) REFERENCES groups (id);

ALTER TABLE daily
    ADD CONSTRAINT FK_DAILY_ON_CHILD FOREIGN KEY (child_id) REFERENCES children (id);

ALTER TABLE groups
    ADD CONSTRAINT FK_GROUPS_ON_TEACHER FOREIGN KEY (teacher_id) REFERENCES users (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_role FOREIGN KEY (roles_id) REFERENCES roles (id);

ALTER TABLE users_roles
    ADD CONSTRAINT fk_userol_on_user FOREIGN KEY (user_id) REFERENCES users (id);